"""
transform/helpers.py

Shared utilities for normalize_cia.py and normalize_ofac.py.
Neither normalizer should define its own constants or helper functions —
everything shared lives here to avoid duplication.

Contains:
    - ABBREVIATIONS: CIA title abbreviation map
    - COUNTRY_OVERRIDES: manual overrides for ambiguous country names
    - make_id(): deterministic UUID5 entity ID generation
    - to_iso_country(): country name → ISO alpha-2 code
    - expand_abbreviations(): expand CIA title abbreviations
    - normalize_date(): normalize various date formats to YYYY-MM-DD
    - split_cia_name(): split CIA "First LAST" format into components
    - verify_country_mappings(): test country mappings against known strings
"""

import re
import uuid
import pycountry
import dateparser
from datetime import datetime

# ─── Debug Flag ───────────────────────────────────────────────────────────────
# Set to True during development to see verbose per-record output.
# Set to False for normal runs — only warnings and errors will print.

DEBUG = False


# ─── Abbreviation Map ─────────────────────────────────────────────────────────
# Built directly from profiler output — all 18 abbreviations found in CIA data.
# Intentionally hardcoded because these are CIA-specific abbreviations,
# not standard English. There is no library for this.
# The profiler gave the complete list so a hardcoded map is the right approach.
#
# "U.", "S.", "Inc." appear once each and are too ambiguous to expand —
# likely part of "U.S." in a title or a data entry error.

ABBREVIATIONS = {
    "Min.":   "Minister",
    "Pres.":  "President",
    "Dep.":   "Deputy",
    "Sec.":   "Secretary",
    "Gen.":   "General",
    "Chmn.":  "Chairman",
    "Govt.":  "Government",
    "Del.":   "Delegate",
    "Admin.": "Administrator",
    "Intl.":  "International",
    "Dir.":   "Director", 
    "Dept.":  "Department",
    "Ctte.":  "Committee",
    "Fed.":   "Federal",
    "Gov.":   "Governor",
}


# ─── Country Overrides ────────────────────────────────────────────────────────
# Manual overrides for country names that pycountry handles incorrectly
# or cannot find at all.
#
# WHY OVERRIDES INSTEAD OF A FULL MAP:
# pycountry covers ~250 countries automatically via fuzzy search.
# Maintaining 200 entries manually is error-prone and hard to update.
# We only manually handle cases pycountry gets wrong:
#   - Non-standard CIA formats: "Bahamas, The", "Korea, North"
#   - Political edge cases: "Taiwan" (not UN-recognized, not in pycountry)
#   - Name mismatches: "Burma" (pycountry uses "Myanmar")
#   - Name changes: "Turkey" (officially "Türkiye" since 2022)

COUNTRY_OVERRIDES = {
    "Korea, North":                      "kp",
    "Korea, South":                      "kr",
    "Burma":                             "mm",  # pycountry uses "Myanmar"
    "Bahamas, The":                      "bs",
    "Gambia, The":                       "gm",
    "Congo, Democratic Republic of the": "cd",
    "Congo, Republic of the":            "cg",
    "Micronesia, Federated States of":   "fm",
    "Holy See":                          "va",
    "Taiwan":                            "tw",  # not UN-recognized, not in pycountry
    "Czechia":                           "cz",
    "Laos":                              "la",  # pycountry uses "Lao People's Dem. Rep."
    "Vietnam":                           "vn",
    "Syria":                             "sy",
    "Iran":                              "ir",
    "Russia":                            "ru",
    "Venezuela":                         "ve",
    "Bolivia":                           "bo",
    "Moldova":                           "md",
    "Turkey":                            "tr",  # officially "Türkiye" since 2022
    "Türkiye":                           "tr",  # in case pycountry returns new name
}


# ─── UUID Namespace ───────────────────────────────────────────────────────────
# Fixed private namespace for UUID5 generation.
# UUID5 is deterministic — same inputs always produce the same UUID.
# Using a fixed private namespace ensures our IDs don't collide with
# UUIDs generated by other systems using standard namespaces like DNS or URL.

_UUID_NAMESPACE = uuid.UUID("b7c9a2e1-4f3d-5a8b-9c0e-1d2f3a4b5c6d")


# ─── Functions ────────────────────────────────────────────────────────────────

def make_id(source, *parts):
    """
    Creates a deterministic UUID5 entity ID from source + identifying parts.

    WHY UUID5 OVER SHA1 HEX:
    UUID5 is the standard way to create deterministic UUIDs from content.
    Built into Python's standard library, produces a standard UUID format
    that databases and APIs understand natively, and is equally
    collision-resistant for our scale (~10,000 entities).

    WHY DETERMINISTIC IDS MATTER:
    If you run the pipeline twice, the same person gets the same ID.
    The database loader can upsert (update or insert) rather than
    blindly inserting duplicates.

    Args:
        source: data source identifier e.g. "cia" or "ofac"
        *parts: identifying strings e.g. country, name, title

    Returns:
        UUID5 string e.g. "3f2504e0-4f89-11d3-9a0c-0305e82c3301"

    Example:
        make_id("cia", "Philippines", "Ferdinand MARCOS, Jr.")
        → uuid5(namespace, "cia:philippines:ferdinand marcos, jr.")
    """
    raw = ":".join([source] + [str(p).lower().strip() for p in parts])
    result = str(uuid.uuid5(_UUID_NAMESPACE, raw))
    if DEBUG:
        print(f"  [DEBUG] make_id({source!r}, {parts}) → {result}")
    return result


def to_iso_country(name):
    """
    Converts a country name string to ISO alpha-2 code (lowercase).

    APPROACH — two-step lookup:
    1. Check COUNTRY_OVERRIDES first for ambiguous/non-standard names
    2. Fall back to pycountry fuzzy search for everything else

    WHY PYCOUNTRY FUZZY SEARCH:
    Handles thousands of name variations automatically.
    "Russian Federation", "Russia", "RUSSIA" all resolve to "ru".

    FALLBACK BEHAVIOR:
    Returns name lowercased if nothing matches — data is never lost.
    A [WARN] is printed so you know what needs adding to COUNTRY_OVERRIDES.

    Args:
        name: country name string e.g. "Russia", "Korea, North"

    Returns:
        ISO alpha-2 code e.g. "ru", "kp"
        or lowercased original string if no match found
    """
    if not name:
        return ""
    name = name.strip()

    # Step 1 — manual overrides for known problem cases
    if name in COUNTRY_OVERRIDES:
        result = COUNTRY_OVERRIDES[name]
        if DEBUG:
            print(f"  [DEBUG] to_iso_country: '{name}' → '{result}' (override)")
        return result

    # Step 2 — pycountry fuzzy search
    try:
        results = pycountry.countries.search_fuzzy(name)
        result = results[0].alpha_2.lower()
        if DEBUG:
            print(f"  [DEBUG] to_iso_country: '{name}' → '{result}' (pycountry)")
        return result
    except LookupError:
        print(f"  [WARN] Country not mapped: '{name}' — storing as-is")
        return name.lower()


def expand_abbreviations(title):
    """
    Expands CIA title abbreviations to their full forms.
    Uses word boundary matching so "Min." doesn't match inside other words.

    LOGGING UNKNOWN ABBREVIATIONS:
    If CIA adds a new abbreviation not in our map, a [WARN] is printed
    instead of silently leaving it unexpanded. Helps catch gaps when
    CIA updates their data format.

    Args:
        title: raw CIA title string e.g. "Dep. Min. of Finance"

    Returns:
        expanded title string e.g. "Deputy Minister of Finance"
    """
    if not title:
        return title

    original = title

    # Warn about any abbreviation-like tokens not in our map
    found_abbrevs = re.findall(r'\b[A-Za-z]+\.', title)
    for abbrev in found_abbrevs:
        if abbrev not in ABBREVIATIONS:
            print(f"  [WARN] Unknown abbreviation '{abbrev}' in title: '{title}'")

    for abbrev, expanded in ABBREVIATIONS.items():
        title = re.sub(r'\b' + re.escape(abbrev), expanded, title)

    if DEBUG and title != original:
        print(f"  [DEBUG] expand_abbreviations: '{original}' → '{title}'")

    return title


def normalize_date(raw):
    """
    Normalizes various OFAC date formats to YYYY-MM-DD where possible.

    WHY DATEPARSER OVER MANUAL strptime CHAIN:
    dateparser handles hundreds of formats automatically and is more
    resilient to new formats appearing in future OFAC data.
    A manual strptime chain breaks silently on unexpected formats.

    WHY WE STILL HANDLE SOME CASES MANUALLY:
    dateparser parses year-only dates like "1938" as "1938-01-01" —
    implying false precision. OFAC uses year-only to indicate genuine
    uncertainty. We preserve "1938" as "1938" to be honest about the data.
    Date ranges also need preprocessing before dateparser sees them.

    Handles all formats from profiler output:
        "1952-10-07"                 → "1952-10-07"  already ISO
        "03 May 1938"                → "1938-05-03"
        "1938"                       → "1938"         year only, preserved
        "May 1938"                   → "1938-05"      month + year
        "1970 to 1972"               → "1970"         range, take start
        "01 Jan 1970 to 31 Dec 1970" → "1970-01-01"   range, take start
        "circa 07 Jul 1966"          → "1966-07-07"   strip circa

    Args:
        raw: raw date string from OFAC data

    Returns:
        normalized date string, or original raw string if unparseable
    """
    if not raw:
        return ""

    raw = raw.strip()
    original = raw

    # Already ISO — return immediately
    if re.match(r'^\d{4}-\d{2}-\d{2}$', raw):
        if DEBUG:
            print(f"  [DEBUG] normalize_date: '{original}' already ISO")
        return raw

    # Year only — preserve as-is BEFORE dateparser adds false "-01-01"
    if re.match(r'^\d{4}$', raw):
        if DEBUG:
            print(f"  [DEBUG] normalize_date: '{original}' → year only, preserved")
        return raw

    # Strip "circa" prefix
    raw = re.sub(r'^circa\s+', '', raw, flags=re.IGNORECASE)

    # Date range — take start only
    if " to " in raw:
        raw = raw.split(" to ")[0].strip()
        if DEBUG:
            print(f"  [DEBUG] normalize_date: range detected, using start: '{raw}'")

    # Year only after stripping range
    if re.match(r'^\d{4}$', raw):
        return raw

    # Month + Year — return as YYYY-MM not YYYY-MM-DD
    try:
        result = datetime.strptime(raw, "%b %Y").strftime("%Y-%m")
        if DEBUG:
            print(f"  [DEBUG] normalize_date: '{original}' → '{result}' (Mon YYYY)")
        return result
    except ValueError:
        pass

    # Let dateparser handle everything else
    result = dateparser.parse(
        raw,
        settings={"PREFER_DATE_SOURCE": "past", "RETURN_AS_TIMEZONE_AWARE": False}
    )
    if result:
        normalized = result.strftime("%Y-%m-%d")
        if DEBUG:
            print(f"  [DEBUG] normalize_date: '{original}' → '{normalized}' (dateparser)")
        return normalized

    # Could not parse
    print(f"  [WARN] Could not normalize date: '{raw}'")
    return original


def split_cia_name(raw_name):
    """
    Splits a CIA name string into first and last name components.

    CIA NAMING CONVENTION:
    Last names are written in ALL CAPS, first names in Title Case.
    e.g. "Ferdinand MARCOS, Jr." — MARCOS is last, Ferdinand is first.

    WHY NOT SPLIT ON COMMA:
    Commas appear as suffix separators ("MARCOS, Jr.") not first/last
    separators. The ALL CAPS rule handles this correctly.

    Args:
        raw_name: raw CIA name string e.g. "Ferdinand MARCOS, Jr."

    Returns:
        tuple (first_name, last_name) strings, either can be None
        returns (None, None) for VACANT or empty — caller should skip
    """
    if not raw_name or "VACANT" in raw_name.upper():
        if DEBUG:
            print(f"  [DEBUG] split_cia_name: '{raw_name}' → skipped (VACANT or empty)")
        return None, None

    parts = raw_name.split()
    first_parts = []
    last_parts = []

    for part in parts:
        clean = re.sub(r'[^A-Za-z]', '', part)
        if clean and clean == clean.upper() and len(clean) > 1:
            last_parts.append(part.title())
        else:
            if last_parts:
                last_parts.append(part)
            else:
                first_parts.append(part)

    first = " ".join(first_parts).strip() or None
    last = " ".join(last_parts).strip() or None

    # Warn if we couldn't extract both components
    if not first and not last:
        print(f"  [WARN] split_cia_name: could not split '{raw_name}'")
    elif not first:
        print(f"  [WARN] split_cia_name: no first name found in '{raw_name}'")
    elif not last:
        print(f"  [WARN] split_cia_name: no last name found in '{raw_name}'")

    if DEBUG:
        print(f"  [DEBUG] split_cia_name: '{raw_name}' → first='{first}' last='{last}'")

    return first, last


# ─── Verification ─────────────────────────────────────────────────────────────

def verify_country_mappings():
    """
    Tests to_iso_country() against all country name strings from profiler output.
    Run once after setup to confirm pycountry resolves everything correctly.
    Any FAIL lines indicate strings to add to COUNTRY_OVERRIDES.

    Usage:
        python transform/helpers.py
    """
    test_names = [
        "Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
        "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia",
        "Austria", "Azerbaijan", "Bahamas, The", "Bahrain", "Bangladesh",
        "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei",
        "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cabo Verde",
        "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad",
        "Chile", "China", "Colombia", "Comoros",
        "Congo, Democratic Republic of the", "Congo, Republic of the",
        "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark",
        "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini",
        "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia, The",
        "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala",
        "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras",
        "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
        "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
        "Kiribati", "Korea, North", "Korea, South", "Kuwait", "Kyrgyzstan",
        "Laos", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
        "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia",
        "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia, Federated States of", "Moldova",
        "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique",
        "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand",
        "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru",
        "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia",
        "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
        "Saint Vincent and the Grenadines", "Samoa", "San Marino",
        "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia",
        "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan",
        "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
        "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga",
        "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
        "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
        "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
        "Vietnam", "Yemen", "Zambia", "Zimbabwe",
        # OFAC nationality strings from profiler
        "Iraq", "Lebanon", "China", "Korea, North", "Ukraine",
        "Burma", "Colombia", "Yemen", "Pakistan", "Turkey",
        "Nicaragua", "India", "Somalia", "Saudi Arabia",
    ]

    print("Verifying country mappings...\n")
    failures = []
    warnings = []

    for name in sorted(set(test_names)):
        result = to_iso_country(name)
        if len(result) == 2:
            status = "OK  "
        else:
            status = "FAIL"
            failures.append((name, result))
        print(f"  {status}  {name:<45} → {result}")

    print(f"\n{'─' * 55}")
    print(f"  {len(test_names) - len(failures)} passed")
    print(f"  {len(failures)} failed")

    if failures:
        print(f"\n  Add these to COUNTRY_OVERRIDES in helpers.py:")
        for name, result in failures:
            print(f'    "{name}": "??",  # got: {result}')
    else:
        print("\n  All country mappings resolved correctly.")


if __name__ == "__main__":
    verify_country_mappings()